# Generated by Django 5.0.6 on 2024-06-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cook', '0005_post_comment_rating_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
